import chalk from "chalk";
import boxen from "boxen";
import { confirm, isCancel, outro } from "@clack/prompts";
import { getStoredKeys, getCurrentProvider } from "../../config/env.ts";
import { PROVIDERS } from "../../config/providers.ts";
import { KEYS_FILE, CONFIG_DIR } from "../../config/env.ts";
import fs from "fs/promises";
import path from "path";

export async function pathAction(): Promise<void> {
  const envPath = path.join(process.cwd(), ".env");

  console.log(chalk.bold("\n📁 Configuration Paths:\n"));
  console.log(`  Config directory: ${chalk.cyan(CONFIG_DIR)}`);
  console.log(`  API keys file:    ${chalk.cyan(KEYS_FILE)}`);
  console.log(`  .env file:        ${chalk.cyan(envPath)}`);
}

export async function initEnvAction(): Promise<void> {
  const envPath = path.join(process.cwd(), ".env");

  try {
    try {
      await fs.readFile(envPath, "utf-8");
      const overwrite = await confirm({
        message: ".env file already exists. Overwrite?",
        initialValue: false,
      });

      if (isCancel(overwrite) || !overwrite) {
        outro(chalk.yellow("Cancelled"));
        return;
      }
    } catch {
    }

    const currentProvider = await getCurrentProvider();
    const provider = PROVIDERS[currentProvider];

    const storedKeys = await getStoredKeys();
    const providerKey = provider?.apiKeyName || "OPENAI_API_KEY";
    const providerValue = process.env[providerKey] || storedKeys[providerKey] || "";
    const exaValue = process.env.EXA_API_KEY || storedKeys.EXA_API_KEY || "";
    const githubValue = process.env.GITHUB_TOKEN || storedKeys.GITHUB_TOKEN || "";
    const modelValue = process.env.AGENTICAI_MODEL || "openai/gpt-5-mini";
    const providerIdValue = process.env.AGENTICAI_PROVIDER || currentProvider;

    const envTemplate = `# agentic CLI Environment Variables
# Generated by: agentic config init-env

# AI Provider Configuration
AGENTICAI_PROVIDER=${providerIdValue}
AGENTICAI_MODEL=${modelValue}

# AI Provider API Key (${provider?.name || "OpenAI"})
${providerKey}=${providerValue}

# Optional: Exa Search API Key (for web search)
# Get one at: https://exa.ai
EXA_API_KEY=${exaValue}

# Optional: GitHub Personal Access Token (for PR reviews)
# Get one at: https://github.com/settings/tokens
GITHUB_TOKEN=${githubValue}
`;

    await fs.writeFile(envPath, envTemplate, "utf-8");

    console.log(
      boxen(
        chalk.green("✅ .env file created successfully!\n") +
        chalk.gray(`Location: ${envPath}\n\n`) +
        chalk.yellow("⚠️  Remember to:"),
        {
          padding: 1,
          borderStyle: "round",
          borderColor: "green",
        }
      )
    );
    console.log(chalk.gray("  1. Fill in your API keys"));
    console.log(chalk.gray("  2. Add .env to .gitignore (if not already)"));
    console.log(chalk.gray("  3. Never commit .env to version control"));

    outro(chalk.green("✨ Done!"));
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error(chalk.red(`Error creating .env file: ${errorMessage}`));
    outro(chalk.red("Failed"));
  }
}

export async function showEnvAction(): Promise<void> {
  const currentProvider = await getCurrentProvider();
  const provider = PROVIDERS[currentProvider];

  console.log(chalk.bold("\n📋 Required Environment Variables:\n"));

  console.log(chalk.cyan("Current Provider:"));
  console.log(chalk.white(`  ${provider.name} (${provider.id})\n`));

  console.log(chalk.bold("Required:"));
  console.log(chalk.green(`  ${provider.apiKeyName}`));
  console.log(chalk.gray(`    ${provider.description}`));
  console.log(chalk.gray(`    Get one at: ${provider.link}\n`));

  console.log(chalk.bold("Optional:"));
  console.log(chalk.yellow("  EXA_API_KEY"));
  console.log(chalk.gray("    Required for web search functionality"));
  console.log(chalk.gray("    Get one at: https://exa.ai\n"));

  console.log(chalk.yellow("  GITHUB_TOKEN"));
  console.log(chalk.gray("    Required for PR review functionality"));
  console.log(chalk.gray("    Get one at: https://github.com/settings/tokens\n"));

  console.log(chalk.bold("Configuration:"));
  console.log(chalk.gray("  AGENTICAI_PROVIDER"));
  console.log(chalk.gray("    Current AI provider ID\n"));
  console.log(chalk.gray("  AGENTICAI_MODEL"));
  console.log(chalk.gray("    Current AI model ID\n"));

  console.log(chalk.bold("\n💡 Setup Methods:\n"));
  console.log(chalk.gray("  1. Interactive setup:"));
  console.log(chalk.white("     agentic config setup\n"));
  console.log(chalk.gray("  2. Initialize .env file:"));
  console.log(chalk.white("     agentic config init-env\n"));
  console.log(chalk.gray("  3. Set individual keys:"));
  console.log(chalk.white("     agentic config set <KEY> <value>\n"));
  console.log(chalk.gray("  4. Manual .env file:"));
  console.log(chalk.white("     Create .env file in your project root\n"));
}
